site_name: Laravel Module Generator
site_description: Opinionated scaffolding for modular Laravel applications.
site_url: https://afshinefati.github.io/laravel-module-generator/
repo_name: AfshinEfati/laravel-module-generator
repo_url: https://github.com/AfshinEfati/laravel-module-generator
nav:
  - en:
      - Home: en/index.md
      - Getting started:
          - Quickstart: en/quickstart.md
          - Installation: en/installation.md
          - Configuration: en/configuration.md
      - Usage: en/usage.md
      - Advanced guides: en/advanced.md
      - Reference:
          - CLI & file reference: en/reference.md
          - Changelog: en/changelog.md
          - GitHub Pages setup: en/github-pages-setup.md
  - fa:
      - صفحه‌ اصلی: fa/index.md
      - شروع سریع:
          - راه‌اندازی فوری: fa/quickstart.md
          - نصب: fa/installation.md
          - پیکربندی: fa/configuration.md
      - کار با ابزار: fa/usage.md
      - راهنمای پیشرفته: fa/advanced.md
      - مرجع:
          - راهنمای مرجع: fa/reference.md
          - تغییرات نسخه‌ها: fa/changelog.md
          - راه‌اندازی GitHub Pages: fa/github-pages-setup.md
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: lime
    - scheme: slate
      primary: indigo
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: "Inter"
    code: "Fira Code"
  features:
    - announce.dismiss
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AfshinEfati/laravel-module-generator
      name: GitHub Repository
extra_css:
  - assets/stylesheets/extra.css
