site_name: Laravel Module Generator Docs
site_description: Documentation for the Laravel Module Generator package.
site_url: https://efati.github.io/laravel-module-generator/
repo_name: efati/laravel-module-generator
repo_url: https://github.com/efati/laravel-module-generator
nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Configuration: configuration.md
  - Usage: usage.md
  - Advanced Features: advanced.md
  - Reference:
      - Changelog: changelog.md
      - GitHub Pages Setup: github-pages-setup.md
      - Information Architecture: ia.md
      - Docsify Sidebar: _sidebar.md
theme:
  name: readthedocs
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
