<?php

namespace Efati\ModuleGenerator\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route;

class SwaggerGenerateCommand extends Command
{
    protected $signature = 'swagger:generate
                            {--output=public/api/swagger.json : Output path for swagger.json}
                            {--title=API Documentation : API title}
                            {--version=1.0.0 : API version}
                            {--host= : Override host}';

    protected $description = 'Generate Swagger/OpenAPI JSON from your routes and controllers';

    public function handle(): int
    {
        $this->info('📄 Generating Swagger documentation...');

        $output = $this->option('output');
        $title = $this->option('title');
        $version = $this->option('version');
        $host = $this->option('host') ?: config('app.url', 'http://localhost');

        // Clean up host URL
        $host = rtrim($host, '/');
        $host = str_replace(['http://', 'https://'], '', $host);

        $swagger = [
            'openapi' => '3.0.0',
            'info' => [
                'title' => $title,
                'description' => 'API Documentation generated by Laravel Module Generator',
                'contact' => [
                    'name' => config('app.name', 'Laravel'),
                    'url' => config('app.url', 'http://localhost'),
                ],
                'version' => $version,
            ],
            'servers' => [
                [
                    'url' => $host,
                    'description' => 'Production Server',
                ],
                [
                    'url' => 'http://localhost:8000',
                    'description' => 'Development Server',
                ],
            ],
            'paths' => $this->extractPaths(),
            'components' => $this->buildComponents(),
        ];

        // Add security schemes if configured
        if ($securitySchemes = config('module-generator.swagger.security.schemes')) {
            $swagger['components']['securitySchemes'] = $securitySchemes;
        }

        // Create output directory
        $outputDir = dirname(base_path($output));
        if (!File::exists($outputDir)) {
            File::makeDirectory($outputDir, 0755, true);
        }

        // Write JSON file
        File::put(
            base_path($output),
            json_encode($swagger, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)
        );

        $this->info('✓ Swagger documentation generated');
        $this->info('');
        $this->info('📍 Location: ' . $this->formatPath(base_path($output)));
        $this->info('');

        return 0;
    }

    protected function extractPaths(): array
    {
        $paths = [];
        $ignoredRoutes = [
            'sanctum',
            'broadcasting',
            'api.docs',
            'docs',
            'swagger',
        ];

        foreach (Route::getRoutes() as $route) {
            // Skip non-API routes
            if (!$this->isApiRoute($route)) {
                continue;
            }

            // Skip ignored routes
            $name = $route->getName() ?? '';
            if ($this->shouldIgnoreRoute($name, $ignoredRoutes)) {
                continue;
            }

            $path = $route->uri();
            $method = strtolower($route->methods[0] ?? 'get');

            if (!isset($paths[$path])) {
                $paths[$path] = [];
            }

            $paths[$path][$method] = $this->buildOperation($route, $method);
        }

        return $paths;
    }

    protected function isApiRoute($route): bool
    {
        $middleware = $route->middleware();

        return in_array('api', $middleware) ||
               str_starts_with($route->uri(), 'api/');
    }

    protected function shouldIgnoreRoute(string $name, array $ignored): bool
    {
        foreach ($ignored as $pattern) {
            if (str_contains($name, $pattern)) {
                return true;
            }
        }
        return false;
    }

    protected function buildOperation($route, string $method): array
    {
        $uri = $route->uri();
        $name = $route->getName() ?? str_replace('/', '.', $uri);

        $operation = [
            'tags' => [$this->extractTag($uri)],
            'summary' => $this->generateSummary($method, $uri),
            'operationId' => $method . ucfirst(str_replace('/', '_', $uri)),
            'description' => 'Auto-generated endpoint from Laravel routes',
        ];

        // Extract path parameters
        if (preg_match_all('/{(\w+)}/', $uri, $matches)) {
            $operation['parameters'] = array_map(function ($param) {
                return [
                    'name' => $param,
                    'in' => 'path',
                    'required' => true,
                    'schema' => ['type' => 'string'],
                ];
            }, $matches[1]);
        }

        // Add query parameters for GET requests
        if ($method === 'get') {
            $operation['parameters'] = ($operation['parameters'] ?? []);
            $operation['parameters'][] = [
                'name' => 'page',
                'in' => 'query',
                'required' => false,
                'schema' => ['type' => 'integer'],
                'description' => 'Page number for pagination',
            ];
            $operation['parameters'][] = [
                'name' => 'limit',
                'in' => 'query',
                'required' => false,
                'schema' => ['type' => 'integer'],
                'description' => 'Number of items per page',
            ];
        }

        // Add request body for POST/PUT/PATCH
        if (in_array($method, ['post', 'put', 'patch'])) {
            $operation['requestBody'] = [
                'required' => true,
                'content' => [
                    'application/json' => [
                        'schema' => ['type' => 'object'],
                    ],
                ],
            ];
        }

        // Add responses
        $operation['responses'] = $this->buildResponses($method);

        // Add security if route has auth middleware
        if ($this->routeRequiresAuth($route)) {
            $operation['security'] = [
                ['bearerAuth' => []],
            ];
        }

        return $operation;
    }

    protected function extractTag(string $uri): string
    {
        $parts = explode('/', $uri);
        // Skip 'api' and 'v1' prefixes
        $tag = collect($parts)
            ->filter(fn ($part) => !in_array($part, ['api', 'v1', 'v2']) && $part !== '')
            ->first();

        return ucfirst($tag ?? 'General');
    }

    protected function generateSummary(string $method, string $uri): string
    {
        $action = match(strtoupper($method)) {
            'GET' => 'List',
            'POST' => 'Create',
            'PUT' => 'Update',
            'PATCH' => 'Partially Update',
            'DELETE' => 'Delete',
            default => ucfirst($method),
        };

        return "{$action} " . str_replace('-', ' ', ucfirst(basename($uri)));
    }

    protected function buildResponses(string $method): array
    {
        return match($method) {
            'get' => [
                '200' => [
                    'description' => 'Success',
                    'content' => [
                        'application/json' => [
                            'schema' => ['type' => 'object'],
                        ],
                    ],
                ],
                '404' => [
                    'description' => 'Not Found',
                ],
            ],
            'post' => [
                '201' => [
                    'description' => 'Created',
                    'content' => [
                        'application/json' => [
                            'schema' => ['type' => 'object'],
                        ],
                    ],
                ],
                '422' => [
                    'description' => 'Validation Error',
                ],
            ],
            'put', 'patch' => [
                '200' => [
                    'description' => 'Updated',
                    'content' => [
                        'application/json' => [
                            'schema' => ['type' => 'object'],
                        ],
                    ],
                ],
                '404' => [
                    'description' => 'Not Found',
                ],
                '422' => [
                    'description' => 'Validation Error',
                ],
            ],
            'delete' => [
                '204' => [
                    'description' => 'Deleted',
                ],
                '404' => [
                    'description' => 'Not Found',
                ],
            ],
            default => [
                '200' => [
                    'description' => 'Success',
                ],
            ],
        };
    }

    protected function buildComponents(): array
    {
        return [
            'schemas' => [
                'Error' => [
                    'type' => 'object',
                    'properties' => [
                        'message' => ['type' => 'string'],
                        'status' => ['type' => 'integer'],
                    ],
                ],
            ],
            'securitySchemes' => [
                'bearerAuth' => [
                    'type' => 'http',
                    'scheme' => 'bearer',
                    'bearerFormat' => 'JWT',
                    'description' => 'Enter a valid bearer token',
                ],
            ],
        ];
    }

    protected function routeRequiresAuth($route): bool
    {
        $middleware = array_map('strtolower', $route->middleware());
        return collect($middleware)->contains(fn ($m) => str_contains($m, 'auth'));
    }

    protected function formatPath(string $path): string
    {
        return str_replace(base_path(), 'app_root', $path);
    }
}
